name: Deploy static content to GitHub Pages

on:
  push:
    branches:
      - main   # Branch iz kojeg se deploy-uje
  workflow_dispatch:  # Omogućava ručno pokretanje

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy_pages:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
